In [2]:
# %load main.py
#1. Import the NUMPY package under the name np.

#[your code here]
import pandas as pd
import numpy as np

In [5]:
#2. Print the NUMPY version and the configuration.

#[your code here]
print ("NumPy version:", np.__version__)

print("\nNumPy configuration:")
print(np.show_config())


NumPy version: 1.26.4

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ironhack_downloads/Library/include
    lib directory: C:/ironhack_downloads/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64

In [11]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#[your code here]
a = np.random.random((2,3,5))


In [13]:
#4. Print a.

#[your code here]
print (a)

[[[0.80664194 0.37307938 0.64891135 0.03791025 0.23915509]
  [0.44624636 0.373316   0.39774432 0.62658184 0.19010291]
  [0.41594506 0.65528785 0.29061383 0.89155038 0.79366961]]

 [[0.68787321 0.7034851  0.46285966 0.72267187 0.02078494]
  [0.02160347 0.68502501 0.89598216 0.46567991 0.79378737]
  [0.47994837 0.71841494 0.92288482 0.21465923 0.29847379]]]


In [19]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#[your code here]
b = np.ones((5,2,3))

In [15]:
#6. Print b.

#[your code here]
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
#7. Do a and b have the same size? How do you prove that in Python code?

#[your code here]
if a.size ==b.size:
    print("a and b have the are the same size")
else:
    print("a and b are not the same size")

a and b have the are the same size


In [17]:
#8. Are you able to add a and b? Why or why not?

#[your code here]
result = a + b

print(result)

#They are different shapes so they cannot be added


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [34]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

#[your code here]
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [24]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

#[your code here]
d= a+c
print(d)
#it works as they are now the same shape

[[[1.80664194 1.37307938 1.64891135 1.03791025 1.23915509]
  [1.44624636 1.373316   1.39774432 1.62658184 1.19010291]
  [1.41594506 1.65528785 1.29061383 1.89155038 1.79366961]]

 [[1.68787321 1.7034851  1.46285966 1.72267187 1.02078494]
  [1.02160347 1.68502501 1.89598216 1.46567991 1.79378737]
  [1.47994837 1.71841494 1.92288482 1.21465923 1.29847379]]]


In [27]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

#[your code here]
print (a)
print("----")
print (d)

#d also contains the sum of c, which is all 1 larger as c was all ones

[[[0.80664194 0.37307938 0.64891135 0.03791025 0.23915509]
  [0.44624636 0.373316   0.39774432 0.62658184 0.19010291]
  [0.41594506 0.65528785 0.29061383 0.89155038 0.79366961]]

 [[0.68787321 0.7034851  0.46285966 0.72267187 0.02078494]
  [0.02160347 0.68502501 0.89598216 0.46567991 0.79378737]
  [0.47994837 0.71841494 0.92288482 0.21465923 0.29847379]]]
----
[[[1.80664194 1.37307938 1.64891135 1.03791025 1.23915509]
  [1.44624636 1.373316   1.39774432 1.62658184 1.19010291]
  [1.41594506 1.65528785 1.29061383 1.89155038 1.79366961]]

 [[1.68787321 1.7034851  1.46285966 1.72267187 1.02078494]
  [1.02160347 1.68502501 1.89598216 1.46567991 1.79378737]
  [1.47994837 1.71841494 1.92288482 1.21465923 1.29847379]]]


In [28]:
#12. Multiply a and c. Assign the result to e.

#[your code here]
e = a*c

In [33]:
#13. Does e equal to a? Why or why not?

#[your code here]
if e.all==a.all:
    print("e and a have the are equal")
else:
    print("e and a are not the equal")

#not equal because 

e and a are not the same size


In [35]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

#[your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [36]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

#[your code here]
f=np.empty_like(d)
print(f)
print(d)

[[[1.80664194 1.37307938 1.64891135 1.03791025 1.23915509]
  [1.44624636 1.373316   1.39774432 1.62658184 1.19010291]
  [1.41594506 1.65528785 1.29061383 1.89155038 1.79366961]]

 [[1.68787321 1.7034851  1.46285966 1.72267187 1.02078494]
  [1.02160347 1.68502501 1.89598216 1.46567991 1.79378737]
  [1.47994837 1.71841494 1.92288482 1.21465923 1.29847379]]]
[[[1.80664194 1.37307938 1.64891135 1.03791025 1.23915509]
  [1.44624636 1.373316   1.39774432 1.62658184 1.19010291]
  [1.41594506 1.65528785 1.29061383 1.89155038 1.79366961]]

 [[1.68787321 1.7034851  1.46285966 1.72267187 1.02078494]
  [1.02160347 1.68502501 1.89598216 1.46567991 1.79378737]
  [1.47994837 1.71841494 1.92288482 1.21465923 1.29847379]]]


In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

#[your code here]
